/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CapacityBadge: typeof import('./src/components/weekly-planner/CapacityBadge.vue')['default']
    ColumnSettings: typeof import('./src/components/ColumnSettings.vue')['default']
    DayCell: typeof import('./src/components/weekly-planner/DayCell.vue')['default']
    HourAllocationModal: typeof import('./src/components/weekly-planner/HourAllocationModal.vue')['default']
    KanbanBoard: typeof import('./src/components/KanbanBoard.vue')['default']
    MilestoneModal: typeof import('./src/components/MilestoneModal.vue')['default']
    MilestonePanel: typeof import('./src/components/MilestonePanel.vue')['default']
    MyTaskCardMobile: typeof import('./src/components/mytasks/MyTaskCardMobile.vue')['default']
    MyTaskFilters: typeof import('./src/components/mytasks/MyTaskFilters.vue')['default']
    MyTaskList: typeof import('./src/components/mytasks/MyTaskList.vue')['default']
    MyTaskRowDesktop: typeof import('./src/components/mytasks/MyTaskRowDesktop.vue')['default']
    OutlinerNav: typeof import('./src/components/OutlinerNav.vue')['default']
    PriorityBadge: typeof import('./src/components/shared/PriorityBadge.vue')['default']
    ProjectInfoPanel: typeof import('./src/components/ProjectInfoPanel.vue')['default']
    ProjectTeam: typeof import('./src/components/ProjectTeam.vue')['default']
    QuickAddTask: typeof import('./src/components/QuickAddTask.vue')['default']
    QuickFilters: typeof import('./src/components/QuickFilters.vue')['default']
    ResourcePoolSummary: typeof import('./src/components/weekly-planner/ResourcePoolSummary.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBadge: typeof import('./src/components/shared/StatusBadge.vue')['default']
    TaskCard: typeof import('./src/components/weekly-planner/TaskCard.vue')['default']
    TaskDetailPanel: typeof import('./src/components/TaskDetailPanel.vue')['default']
    TaskPool: typeof import('./src/components/weekly-planner/TaskPool.vue')['default']
    TaskRow: typeof import('./src/components/TaskRow.vue')['default']
    TaskTree: typeof import('./src/components/TaskTree.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    TimelineView: typeof import('./src/components/TimelineView.vue')['default']
    TimeLogModal: typeof import('./src/components/TimeLogModal.vue')['default']
    UserSelect: typeof import('./src/components/UserSelect.vue')['default']
    WeeklyPlannerGrid: typeof import('./src/components/weekly-planner/WeeklyPlannerGrid.vue')['default']
    WeeklyPlannerHeader: typeof import('./src/components/weekly-planner/WeeklyPlannerHeader.vue')['default']
  }
}
