/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    KanbanBoard: typeof import('./src/components/KanbanBoard.vue')['default']
    MilestoneModal: typeof import('./src/components/MilestoneModal.vue')['default']
    MilestonePanel: typeof import('./src/components/MilestonePanel.vue')['default']
    MyTaskCardMobile: typeof import('./src/components/mytasks/MyTaskCardMobile.vue')['default']
    MyTaskDrawer: typeof import('./src/components/mytasks/MyTaskDrawer.vue')['default']
    MyTaskFilters: typeof import('./src/components/mytasks/MyTaskFilters.vue')['default']
    MyTaskList: typeof import('./src/components/mytasks/MyTaskList.vue')['default']
    MyTaskRowDesktop: typeof import('./src/components/mytasks/MyTaskRowDesktop.vue')['default']
    PriorityBadge: typeof import('./src/components/shared/PriorityBadge.vue')['default']
    ProjectInfoPanel: typeof import('./src/components/ProjectInfoPanel.vue')['default']
    ProjectTeam: typeof import('./src/components/ProjectTeam.vue')['default']
    QuickAddTask: typeof import('./src/components/QuickAddTask.vue')['default']
    QuickFilters: typeof import('./src/components/QuickFilters.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBadge: typeof import('./src/components/shared/StatusBadge.vue')['default']
    TaskDetailPanel: typeof import('./src/components/TaskDetailPanel.vue')['default']
    TaskRow: typeof import('./src/components/TaskRow.vue')['default']
    TaskTree: typeof import('./src/components/TaskTree.vue')['default']
    TimeLogModal: typeof import('./src/components/TimeLogModal.vue')['default']
    UserSelect: typeof import('./src/components/UserSelect.vue')['default']
  }
}
